apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-redes-avancadas-lab-es
  namespace: girus
  labels:
    app: girus-lab-template
data:
  lab.yaml: |
    name: docker-redes-avancadas-es
    title: "Redes Avanzadas en Docker"
    description: "Aprende a configurar y administrar redes avanzadas en Docker, incluyendo redes personalizadas, comunicación entre contenedores y aislamiento de red. Este laboratorio guiado explora los conceptos avanzados de networking en Docker y cómo implementar arquitecturas de red complejas."
    duration: 35m
    image: "linuxtips/girus-devops:0.1"
    privileged: true
    tasks:
      - name: "Creación de Redes Personalizadas"
        description: "Aprende a crear y administrar redes Docker personalizadas."
        steps:
          - description: "Crea una red bridge personalizada"
            command: "docker network create --driver bridge mi-red"
            expectedOutput: ""
            hint: "Usa el comando docker network create para crear una red"

          - description: "Verifica las redes disponibles"
            command: "docker network ls"
            expectedOutput: "mi-red"
            hint: "Usa el comando docker network ls para listar las redes"

          - description: "Inspecciona la red creada"
            command: "docker network inspect mi-red"
            expectedOutput: "Name: mi-red"
            hint: "Usa el comando docker network inspect para ver detalles de la red"

      - name: "Comunicación entre Contenedores"
        description: "Configura la comunicación entre contenedores en diferentes redes."
        steps:
          - description: "Crea un contenedor en la red personalizada"
            command: "docker run -d --name web --network mi-red nginx"
            expectedOutput: ""
            hint: "Usa el comando docker run con --network para conectar a la red"

          - description: "Crea otro contenedor en la misma red"
            command: "docker run -d --name db --network mi-red -e MYSQL_ROOT_PASSWORD=password mysql:5.7"
            expectedOutput: ""
            hint: "Crea otro contenedor en la misma red"

          - description: "Prueba la comunicación entre contenedores"
            command: "docker exec web ping -c 4 db"
            expectedOutput: "4 packets transmitted"
            hint: "Usa el comando docker exec para probar la conectividad"

      - name: "Aislamiento y Seguridad de Red"
        description: "Implementa aislamiento y seguridad en redes Docker."
        steps:
          - description: "Crea una red aislada"
            command: "docker network create --internal red-aislada"
            expectedOutput: ""
            hint: "Usa la opción --internal para crear una red aislada"

          - description: "Crea un contenedor en la red aislada"
            command: "docker run -d --name app-aislado --network red-aislada nginx"
            expectedOutput: ""
            hint: "Crea un contenedor en la red aislada"

          - description: "Verifica el aislamiento"
            command: "docker exec app-aislado ping -c 4 8.8.8.8"
            expectedOutput: "Network is unreachable"
            hint: "Intenta acceder a internet desde el contenedor aislado"
