apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-deployments-replicasets-lab-es
  namespace: girus
  labels:
    app: girus-lab-template
data:
  lab.yaml: |
    name: kubernetes-deployments-replicasets-es
    title: "Deployments e ReplicaSets no Kubernetes"
    description: "aprende a administrar aplicações no Kubernetes usando Deployments e ReplicaSets. Este laboratorio guiado explora conceitos fundamentais de orquestração de containers, escalabilidade e alta disponibilidade."
    duration: 40m
    image: "linuxtips/girus-devops:0.1"
    privileged: true
    tasks:
      - name: "creando un Deployment Básico"
        description: "aprende a crear e administrar Deployments no Kubernetes."
        steps:
          - description: "crea un Deployment do nginx"
            command: "kubectl create deployment nginx-deployment --image=nginx:1.21"
            expectedOutput: "deployment.apps/nginx-deployment created"
            hint: "Use o comando kubectl create deployment"

          - description: "verifique o status do Deployment"
            command: "kubectl get deployments"
            expectedOutput: "nginx-deployment"
            hint: "Use o comando kubectl get deployments"

          - description: "verifique os Pods criados"
            command: "kubectl get pods"
            expectedOutput: "nginx-deployment"
            hint: "Use o comando kubectl get pods"

      - name: "Escalando Deployments"
        description: "aprende a escalar aplicações no Kubernetes."
        steps:
          - description: "Escale o Deployment para 3 réplicas"
            command: "kubectl scale deployment nginx-deployment --replicas=3"
            expectedOutput: "deployment.apps/nginx-deployment scaled"
            hint: "Use o comando kubectl scale deployment"

          - description: "verifique as réplicas"
            command: "kubectl get pods"
            expectedOutput: "nginx-deployment"
            hint: "verifique os pods em execução"

          - description: "verifique o ReplicaSet"
            command: "kubectl get rs"
            expectedOutput: "nginx-deployment"
            hint: "Use o comando kubectl get rs para ver o ReplicaSet"

      - name: "Atualizações e Rollbacks"
        description: "Implemente estratégias de actualización e rollback."
        steps:
          - description: "Atualize a imagen do Deployment"
            command: "kubectl set image deployment/nginx-deployment nginx=nginx:1.22"
            expectedOutput: "deployment.apps/nginx-deployment image updated"
            hint: "Use o comando kubectl set image"

          - description: "verifique o histórico de revisões"
            command: "kubectl rollout history deployment/nginx-deployment"
            expectedOutput: "deployment.apps/nginx-deployment"
            hint: "Use o comando kubectl rollout history"

          - description: "Faça rollback para a versão anterior"
            command: "kubectl rollout undo deployment/nginx-deployment"
            expectedOutput: "deployment.apps/nginx-deployment rolled back"
            hint: "Use o comando kubectl rollout undo"
