apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-s3-iam-lab-es
  namespace: girus
  labels:
    app: girus-lab-template
data:
  lab.yaml: |
    name: aws-s3-iam-es
    title: "S3 e IAM en AWS"
    description: "Aprende a administrar buckets S3 y políticas IAM en AWS. Este laboratorio guiado explora conceptos de almacenamiento de objetos y control de acceso en la nube."
    duration: 40m
    image: "linuxtips/girus-devops:0.1"
    privileged: true
    tasks:
      - name: "Administración de Buckets S3"
        description: "Aprende a crear y configurar buckets S3."
        steps:
          - description: "Crea un bucket S3"
            command: "aws s3api create-bucket --bucket lab-bucket-$(date +%s) --region us-east-1"
            expectedOutput: "Location"
            hint: "Usa el comando aws s3api create-bucket"

          - description: "Configura el bucket para hospedaje de sitio web estático"
            command: "aws s3api put-bucket-website --bucket $(aws s3api list-buckets --query 'Buckets[0].Name' --output text) --website-configuration '{\"IndexDocument\":{\"Suffix\":\"index.html\"},\"ErrorDocument\":{\"Key\":\"error.html\"}}'"
            expectedOutput: ""
            hint: "Usa el comando aws s3api put-bucket-website"

          - description: "Configura la política del bucket"
            command: "aws s3api put-bucket-policy --bucket $(aws s3api list-buckets --query 'Buckets[0].Name' --output text) --policy '{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"PublicReadGetObject\",\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":\"s3:GetObject\",\"Resource\":\"arn:aws:s3:::$(aws s3api list-buckets --query \"Buckets[0].Name\" --output text)/*\"}]}'"
            expectedOutput: ""
            hint: "Usa el comando aws s3api put-bucket-policy"

      - name: "Operaciones con Objetos S3"
        description: "Aprende a administrar objetos en buckets S3."
        steps:
          - description: "Crea un archivo de prueba"
            command: "echo '<html><body><h1>Hello from S3!</h1></body></html>' > index.html"
            expectedOutput: ""
            hint: "Crea un archivo HTML simple"

          - description: "Sube el archivo al bucket"
            command: "aws s3 cp index.html s3://$(aws s3api list-buckets --query 'Buckets[0].Name' --output text)/"
            expectedOutput: "upload:"
            hint: "Usa el comando aws s3 cp"

          - description: "Verifica el contenido del bucket"
            command: "aws s3 ls s3://$(aws s3api list-buckets --query 'Buckets[0].Name' --output text)/"
            expectedOutput: "index.html"
            hint: "Usa el comando aws s3 ls"

      - name: "Administración de IAM"
        description: "Aprende a crear y administrar usuarios y políticas IAM."
        steps:
          - description: "Crea un usuario IAM"
            command: "aws iam create-user --user-name lab-user"
            expectedOutput: "User"
            hint: "Usa el comando aws iam create-user"

          - description: "Crea una política de acceso a S3"
            command: "aws iam create-policy --policy-name S3AccessPolicy --policy-document '{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":[\"s3:GetObject\",\"s3:PutObject\"],\"Resource\":\"arn:aws:s3:::$(aws s3api list-buckets --query \"Buckets[0].Name\" --output text)/*\"}]}'"
            expectedOutput: "Policy"
            hint: "Usa el comando aws iam create-policy"

          - description: "Asocia la política al usuario"
            command: "aws iam attach-user-policy --user-name lab-user --policy-arn $(aws iam list-policies --query 'Policies[0].Arn' --output text)"
            expectedOutput: ""
            hint: "Usa el comando aws iam attach-user-policy"
