apiVersion: v1
kind: ConfigMap
metadata:
  name: linux-redes-conectividade-lab-es
  namespace: girus
  labels:
    app: girus-lab-template
data:
  lab.yaml: |
    name: linux-redes-conectividade-es
    title: "Redes y Conectividad en Linux"
    description: "Aprende a configurar y administrar redes en Linux, incluyendo interfaces de red, enrutamiento, firewall y diagnóstico de problemas de conectividad. Este laboratorio guiado explora los comandos y herramientas esenciales para administración de redes en sistemas Linux, proporcionando una base sólida para solución de problemas de conectividad."
    duration: 30m
    image: "linuxtips/girus-devops:0.1"
    tasks:
      - name: "Configuración de Interfaces de Red"
        description: "Aprende a configurar y administrar interfaces de red en Linux, incluyendo direccionamiento IP, máscaras de subred y gateways."
        steps:
          - description: "Verifica las interfaces de red disponibles"
            command: "ip addr show"
            expectedOutput: "eth0"
            hint: "Usa el comando ip addr show para listar todas las interfaces de red"

          - description: "Configura una dirección IP estática"
            command: "ip addr add 192.168.1.100/24 dev eth0"
            expectedOutput: ""
            hint: "Usa el comando ip addr add para configurar una dirección IP"

          - description: "Verifica la conectividad de red"
            command: "ping -c 4 8.8.8.8"
            expectedOutput: "4 packets transmitted"
            hint: "Usa el comando ping para probar la conectividad"

      - name: "Enrutamiento y Firewall"
        description: "Explora el enrutamiento y configuración de firewall en Linux usando iptables y herramientas de diagnóstico."
        steps:
          - description: "Verifica la tabla de enrutamiento"
            command: "ip route show"
            expectedOutput: "default via"
            hint: "Usa el comando ip route show para ver las rutas configuradas"

          - description: "Configura una regla de firewall básica"
            command: "iptables -A INPUT -p tcp --dport 80 -j ACCEPT"
            expectedOutput: ""
            hint: "Usa el comando iptables para configurar reglas de firewall"

          - description: "Verifica las reglas de firewall"
            command: "iptables -L"
            expectedOutput: "Chain INPUT"
            hint: "Usa el comando iptables -L para listar las reglas"

      - name: "Diagnóstico de Problemas"
        description: "Aprende a diagnosticar y resolver problemas comunes de red en Linux."
        steps:
          - description: "Verifica el estado de la red"
            command: "netstat -tuln"
            expectedOutput: "Active Internet connections"
            hint: "Usa el comando netstat para ver conexiones activas"

          - description: "Prueba la resolución DNS"
            command: "dig google.com"
            expectedOutput: ";; ANSWER SECTION:"
            hint: "Usa el comando dig para probar la resolución DNS"

          - description: "Analiza el tráfico de red"
            command: "tcpdump -i eth0 -c 5"
            expectedOutput: "tcpdump: listening on eth0"
            hint: "Usa el comando tcpdump para capturar paquetes de red"
