name: Build Status

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  badge:
    name: Update Build Status Badge
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Generate Badge
        uses: RubbaBoy/BYOB@24f464284c1fd32028524b59607d417a2e36fee7 # v1.3.0
        with:
          NAME: build
          LABEL: build
          STATUS: ${{ job.status }}
          COLOR: green
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
