name: Docker

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions: {}

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0  # Fetch all history for tags and branches

      - name: Determine version
        id: version
        run: |
          # Check if this is a tag build
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            # If not a tag, use the latest tag + commit hash
            LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
            LATEST_TAG=${LATEST_TAG#v}  # Remove 'v' prefix if present
            COMMIT_SHORT=$(git rev-parse --short HEAD)
            VERSION="${LATEST_TAG}-dev.${COMMIT_SHORT}"
          fi
          
          echo "Determined version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: linuxtips
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: linuxtips/girus-cli
          tags: |
            type=sha,format=short
            type=raw,value=latest
            type=raw,value=${{ env.VERSION }}
            type=semver,pattern={{version}},value=${{ env.VERSION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.VERSION }}

      - name: Verify Docker image
        run: |
          docker pull linuxtips/girus-cli:${{ env.VERSION }}
          docker run --rm linuxtips/girus-cli:${{ env.VERSION }} version
